services:
  - type: web
    name: kool-m3u-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    healthCheckPath: /health
    plan: free
